version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./Spring/.env
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE="tpachato"
    ports:
      - $MYSQLDB_LOCAL_PORT:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./Spring
    restart: on-failure
    env_file: ./Spring/.env
    ports:
      - $SPRING_LOCAL_PORT:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/$tpachato?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/home/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  front:
    depends_on:
      - app
    build: ./Angular/crud-tuto-front/
    ports:
      - 4201:4201
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
